# Generated by Django 2.2.8 on 2019-12-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trips',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
