# Generated by Django 2.2.8 on 2019-12-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_locations', '0003_auto_20191226_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='trips',
            unique_together={('city', 'country', 'start_date')},
        ),
    ]
