# Generated by Django 2.2.8 on 2019-12-26 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_locations', '0004_auto_20191226_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='trips',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trips',
            unique_together={('traveler', 'city', 'country', 'start_date')},
        ),
    ]
