# Generated by Django 2.2.8 on 2019-12-28 19:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map_locations', '0006_auto_20191226_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trips',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
