# Generated by Django 2.2.8 on 2020-01-18 17:47

from django.db import migrations, models
import map_locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locations', '0011_auto_20200118_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimages',
            name='image',
            field=models.ImageField(upload_to=map_locations.models.user_directory_path),
        ),
    ]
