# Generated by Django 2.2.8 on 2020-01-18 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_locations', '0012_auto_20200118_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimages',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
